In [37]:
#LIBRERIAS A USAR
import pandas as pd
import numpy as np
import warnings
from IPython.display import Image, display
import os
warnings.filterwarnings('ignore')

In [38]:
movies_df_filepath = os.path.abspath("dataset/movies_original.csv")
ratings_df_filepath = os.path.abspath("dataset/ratings_original.csv")
poster_df_filepath = os.path.abspath("dataset/MovieGenre.csv")

#CARGA DE LOS DATASETS
movies_df = pd.read_csv(movies_df_filepath)
ratings_df = pd.read_csv(ratings_df_filepath)
posters_df = pd.read_csv(poster_df_filepath, encoding='latin-1')

In [39]:
movies_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
34203,151697,Grand Slam (1967),Thriller
34204,151701,Bloodmoney (2010),(no genres listed)
34205,151703,The Butterfly Circus (2009),Drama
34206,151709,Zero (2015),Drama|Sci-Fi
34207,151711,The 2000 Year Old Man (1975),(no genres listed)

In [40]:
movies_df['year'] = movies_df['title'].str.extract('(\(\d{4}\))', expand=False)

In [41]:
movies_df

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,(1995)
1,2,Jumanji (1995),Adventure|Children|Fantasy,(1995)
2,3,Grumpier Old Men (1995),Comedy|Romance,(1995)
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,(1995)
4,5,Father of the Bride Part II (1995),Comedy,(1995)
...,...,...,...,...
34203,151697,Grand Slam (1967),Thriller,(1967)
34204,151701,Bloodmoney (2010),(no genres listed),(2010)
34205,151703,The Butterfly Circus (2009),Drama,(2009)
34206,151709,Zero (2015),Drama|Sci-Fi,(2015)
34207,151711,The 2000 Year Old Man (1975),(no genres listed),(1975)

In [42]:
#REMOVER PARENTESIS DE LA COLUMNA 'YEAR'
movies_df['year'] = movies_df.year.str.extract('(\d{4})', expand = False)

In [43]:
movies_df

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995
...,...,...,...,...
34203,151697,Grand Slam (1967),Thriller,1967
34204,151701,Bloodmoney (2010),(no genres listed),2010
34205,151703,The Butterfly Circus (2009),Drama,2009
34206,151709,Zero (2015),Drama|Sci-Fi,2015
34207,151711,The 2000 Year Old Man (1975),(no genres listed),1975

In [44]:
#REMOVER EL AÑO DE LA COLUMNA TITULO
movies_df['title'] = movies_df.title.str.replace(r"\s+\(.*\)", "", regex = True)

In [45]:
movies_df

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995
...,...,...,...,...
34203,151697,Grand Slam,Thriller,1967
34204,151701,Bloodmoney,(no genres listed),2010
34205,151703,The Butterfly Circus,Drama,2009
34206,151709,Zero,Drama|Sci-Fi,2015
34207,151711,The 2000 Year Old Man,(no genres listed),1975

In [46]:
#CONVERTIR LA COLUMNA DE GENEROS EN UNA LISTA(VECTOR)
movies_df['genres'] = movies_df['genres'].str.split('|')

In [47]:
movies_df

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995
...,...,...,...,...
34203,151697,Grand Slam,[Thriller],1967
34204,151701,Bloodmoney,[(no genres listed)],2010
34205,151703,The Butterfly Circus,[Drama],2009
34206,151709,Zero,"[Drama, Sci-Fi]",2015
34207,151711,The 2000 Year Old Man,[(no genres listed)],1975

In [48]:
movies_df = movies_df[movies_df['genres'].apply(lambda g: '(no genres listed)' not in g)]

In [49]:
#OBTENER UNA COPIA DEL DATAFRAME ORIGINAL
moviesWithGenres_df = movies_df.copy()

In [50]:
#PARA CADA ROW EN EL DATAFRAME VAMOS A ITERAR SOBRE LOS GENEROS Y ASIGNAR UN 1 EN LA COLUMNA CORRESPONDIENTE

for index, row in movies_df.iterrows():
    for genres in row['genres']:
        if genres != '(no genres listed)':
            moviesWithGenres_df.at[index,genres] = 1
moviesWithGenres_df = moviesWithGenres_df.fillna(0)
moviesWithGenres_df

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,...,Thriller,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men,"[Comedy, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II,[Comedy],1995,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34201,151691,Hollywood High,[Comedy],1976,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34202,151695,The Survivalist,"[Drama, Sci-Fi, Thriller]",2015,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
34203,151697,Grand Slam,[Thriller],1967,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34205,151703,The Butterfly Circus,[Drama],2009,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34206,151709,Zero,"[Drama, Sci-Fi]",2015,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
ratings_df

          userId  movieId  rating   timestamp
0              1      169     2.5  1204927694
1              1     2471     3.0  1204927438
2              1    48516     5.0  1204927435
3              2     2571     3.5  1436165433
4              2   109487     4.0  1436165496
...          ...      ...     ...         ...
22884372  247753    49530     5.0  1430437962
22884373  247753    69481     3.0  1430437984
22884374  247753    74458     4.0  1430437968
22884375  247753    76093     5.0  1430437811
22884376  247753   130636     0.5  1430437721

[22884377 rows x 4 columns]

In [52]:
#USANDO LAMBDA CON AXIS = 0 PARA ENCONTRAR MAXIMO DE RATINGS Y MINIMA DE RATINGS(POR COLUMNAS)
max_Ratings = ratings_df['rating'].max()
min_Ratings = ratings_df['rating'].min()
print(max_Ratings, min_Ratings)

5.0 0.5

In [53]:
#BORRAR COLUMNA DE TIMESTAMP
ratings_df = ratings_df.drop('timestamp', axis = 1) 
ratings_df

          userId  movieId  rating
0              1      169     2.5
1              1     2471     3.0
2              1    48516     5.0
3              2     2571     3.5
4              2   109487     4.0
...          ...      ...     ...
22884372  247753    49530     5.0
22884373  247753    69481     3.0
22884374  247753    74458     4.0
22884375  247753    76093     5.0
22884376  247753   130636     0.5

[22884377 rows x 3 columns]

In [ ]:
#ENTRADA DE DATOS

""" usuario_en = [
    {"title": "Breakfast Club, The", "rating": 4},
    {"title": "Toy Story", "rating": 5},
    {"title": "Jumanji", "rating": 3},
    {"title": "Pulp Fiction", "rating": 5},
    {"title": "Akira", "rating": 4.5}
] """

usuario_en = int(input('Ingrese el id de la pelicula:'))

if usuario_en not in ratings_df['userId'].values:
    print("El usuario no existe")
    raise SystemExit

In [55]:
entrada_peli = ratings_df[ratings_df['userId'] == usuario_en][['movieId', 'rating']]

In [56]:
# Unir con títulos
entrada_peli = pd.merge(
    entrada_peli,
    movies_df[['movieId', 'title']],
    on='movieId',
    how='inner'
)

In [57]:
entrada_peli

    movieId  rating                                           title
0        50     4.0                             Usual Suspects, The
1       260     4.0              Star Wars: Episode IV - A New Hope
2       318     3.5                       Shawshank Redemption, The
3       527     4.0                                Schindler's List
4       858     3.5                                  Godfather, The
5      1196     4.0  Star Wars: Episode V - The Empire Strikes Back
6      1198     4.0                         Raiders of the Lost Ark
7      1917     4.0                                      Armageddon
8      2706     1.5                                    American Pie
9      2959     4.0                                      Fight Club
10     3147     4.5                                 Green Mile, The
11     4226     5.0                                         Memento
12     5618     5.0                                   Spirited Away
13    58559     5.0                                Dark Knight, The
14    79132     5.0                                       Inception
15   109487     5.0                                    Interstellar
16   115713     4.0                                      Ex Machina
17   122886     5.0      Star Wars: Episode VII - The Force Awakens
18   134130     5.0                                    Martian, The
19   134853     5.0                                      Inside Out

In [58]:
#VAMOS A AGREGAR EL ID A NUESTRAS PELICULAS DEL USUARIO, POR NOMBRE

id = movies_df[movies_df['title'].isin(entrada_peli['title'].tolist())]

entrada_peli = pd.merge(id, entrada_peli, how="inner", on = None, validate='many_to_many')

entrada_peli

,movieId,title,genres,year,rating
0,50,"Usual Suspects, The","[Crime, Mystery, Thriller]",1995,4.0
1,260,Star Wars: Episode IV - A New Hope,"[Action, Adventure, Sci-Fi]",1977,4.0
2,318,"Shawshank Redemption, The","[Crime, Drama]",1994,3.5
3,527,Schindler's List,"[Drama, War]",1993,4.0
4,858,"Godfather, The","[Crime, Drama]",1972,3.5
5,1196,Star Wars: Episode V - The Empire Strikes Back,"[Action, Adventure, Sci-Fi]",1980,4.0
6,1198,Raiders of the Lost Ark,"[Action, Adventure]",1981,4.0
7,1917,Armageddon,"[Action, Romance, Sci-Fi, Thriller]",1998,4.0
8,2706,American Pie,"[Comedy, Romance]",1999,1.5
9,2959,Fight Club,"[Action, Crime, Drama, Thriller]",1999,4.0
10,3147,"Green Mile, The","[Crime, Drama]",1999,4.5
11,4226,Memento,"[Mystery, Thriller]",2000,5.0
12,5618,Spirited Away,"[Adventure, Animation, Fantasy]",2001,5.0
13,58559,"Dark Knight, The","[Action, Crime, Drama, IMAX]",2008,5.0
14,79132,Inception,"[Action, Crime, Drama, Mystery, Sci-Fi, Thrill...",2010,5.0
15,109487,Interstellar,"[Sci-Fi, IMAX]",2014,5.0
16,115713,Ex Machina,"[Drama, Sci-Fi, Thriller]",2015,4.0
17,122886,Star Wars: Episode VII - The Force Awakens,"[Action, Adventure, Fantasy, Sci-Fi]",2015,5.0
18,134130,"Martian, The","[Action, Adventure, Sci-Fi]",2015,5.0
19,134853,Inside Out,"[Animation, Children, Comedy]",2015,5.0

In [59]:
# ELIMINAMOS INFO INNECESARIA

entrada_peli = entrada_peli.drop('genres', axis = 1).drop('year', axis = 1)

entrada_peli

    movieId                                           title  rating
0        50                             Usual Suspects, The     4.0
1       260              Star Wars: Episode IV - A New Hope     4.0
2       318                       Shawshank Redemption, The     3.5
3       527                                Schindler's List     4.0
4       858                                  Godfather, The     3.5
5      1196  Star Wars: Episode V - The Empire Strikes Back     4.0
6      1198                         Raiders of the Lost Ark     4.0
7      1917                                      Armageddon     4.0
8      2706                                    American Pie     1.5
9      2959                                      Fight Club     4.0
10     3147                                 Green Mile, The     4.5
11     4226                                         Memento     5.0
12     5618                                   Spirited Away     5.0
13    58559                                Dark Knight, The     5.0
14    79132                                       Inception     5.0
15   109487                                    Interstellar     5.0
16   115713                                      Ex Machina     4.0
17   122886      Star Wars: Episode VII - The Force Awakens     5.0
18   134130                                    Martian, The     5.0
19   134853                                      Inside Out     5.0

In [60]:
#CODIFICAR LAS PELICULAS DEL USUARIO PARA ASIGNAR ONE HOT ENCODING

peli_usuario = moviesWithGenres_df[moviesWithGenres_df['movieId'].isin(entrada_peli['movieId'].tolist())]

peli_usuario

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,...,Thriller,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir
49,50,"Usual Suspects, The","[Crime, Mystery, Thriller]",1995,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
257,260,Star Wars: Episode IV - A New Hope,"[Action, Adventure, Sci-Fi]",1977,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
315,318,"Shawshank Redemption, The","[Crime, Drama]",1994,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
523,527,Schindler's List,"[Drama, War]",1993,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
843,858,"Godfather, The","[Crime, Drama]",1972,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1171,1196,Star Wars: Episode V - The Empire Strikes Back,"[Action, Adventure, Sci-Fi]",1980,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1173,1198,Raiders of the Lost Ark,"[Action, Adventure]",1981,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1834,1917,Armageddon,"[Action, Romance, Sci-Fi, Thriller]",1998,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2621,2706,American Pie,"[Comedy, Romance]",1999,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2874,2959,Fight Club,"[Action, Crime, Drama, Thriller]",1999,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3061,3147,"Green Mile, The","[Crime, Drama]",1999,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4133,4226,Memento,"[Mystery, Thriller]",2000,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5520,5618,Spirited Away,"[Adventure, Animation, Fantasy]",2001,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12540,58559,"Dark Knight, The","[Action, Crime, Drama, IMAX]",2008,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
15562,79132,Inception,"[Action, Crime, Drama, Mystery, Sci-Fi, Thrill...",2010,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
23044,109487,Interstellar,"[Sci-Fi, IMAX]",2014,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
24618,115713,Ex Machina,"[Drama, Sci-Fi, Thriller]",2015,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
26470,122886,Star Wars: Episode VII - The Force Awakens,"[Action, Adventure, Fantasy, Sci-Fi]",2015,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
29257,134130,"Martian, The","[Action, Adventure, Sci-Fi]",2015,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
29494,134853,Inside Out,"[Animation, Children, Comedy]",2015,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [61]:
peli_usuario = peli_usuario.reset_index(drop=True)
tabla_generos = peli_usuario.drop('movieId', axis = 1).drop('genres', axis=1).drop('title', axis=1).drop('year', axis=1)

tabla_generos

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [62]:
#INICIAMOS EL MODELO DE LA MATRIX DE PESO
tabla_generos.transpose()
tabla_generos

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [63]:
entrada_peli['rating']

0     4.0
1     4.0
2     3.5
3     4.0
4     3.5
5     4.0
6     4.0
7     4.0
8     1.5
9     4.0
10    4.5
11    5.0
12    5.0
13    5.0
14    5.0
15    5.0
16    4.0
17    5.0
18    5.0
19    5.0
Name: rating, dtype: float64

In [64]:
perfil_usu = tabla_generos.transpose().dot(entrada_peli['rating'])
perfil_usu

Adventure      27.0
Animation      10.0
Children        5.0
Comedy          6.5
Fantasy        10.0
Romance         5.5
Drama          33.5
Action         40.0
Crime          29.5
Thriller       26.0
Horror          0.0
Mystery        14.0
Sci-Fi         36.0
IMAX           15.0
Documentary     0.0
War             4.0
Musical         0.0
Western         0.0
Film-Noir       0.0
dtype: float64

In [65]:
#MOSTRAMOS LOS GENEROS DE LA TABLA ORIGINAL
generos = moviesWithGenres_df.set_index(moviesWithGenres_df['movieId'])

generos

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,...,Thriller,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir
movieId,,,,,,,,,,,,,,,,,,,,,
1,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,Jumanji,"[Adventure, Children, Fantasy]",1995,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,Grumpier Old Men,"[Comedy, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,5,Father of the Bride Part II,[Comedy],1995,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151691,151691,Hollywood High,[Comedy],1976,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151695,151695,The Survivalist,"[Drama, Sci-Fi, Thriller]",2015,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
151697,151697,Grand Slam,[Thriller],1967,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151703,151703,The Butterfly Circus,[Drama],2009,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151709,151709,Zero,"[Drama, Sci-Fi]",2015,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
generos = generos.drop('title', axis= 1).drop('year', axis= 1).drop('genres', axis= 1)

generos

,movieId,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir
movieId,,,,,,,,,,,,,,,,,,,,
1,1,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151691,151691,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151695,151695,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
151697,151697,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151703,151703,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151709,151709,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
#REALIZAR PROMEDIO PONDERADO
recom = pd.DataFrame(generos['movieId'])
recom['ponderation'] = ((generos * perfil_usu).sum(axis=1)) / (perfil_usu.sum())

recom = pd.DataFrame(recom)

recom

         movieId  ponderation
movieId
1              1     0.223282
2              2     0.160305
3              3     0.045802
4              4     0.173664
5              5     0.024809
...          ...          ...
151691    151691     0.024809
151695    151695     0.364504
151697    151697     0.099237
151703    151703     0.127863
151709    151709     0.265267

[33063 rows x 2 columns]

In [68]:
recom = recom.sort_values(by = 'ponderation', ascending= False)

recom.head(20)

         movieId  ponderation
movieId
115479    115479     0.748092
79132      79132     0.740458
26701      26701     0.721374
5018        5018     0.696565
198          198     0.683206
71999      71999     0.679389
81132      81132     0.673664
67070      67070     0.648855
59844      59844     0.648855
91056      91056     0.633588
37462      37462     0.629771
75408      75408     0.629771
2985        2985     0.629771
519          519     0.629771
76153      76153     0.629771
60684      60684     0.627863
8361        8361     0.620229
122787    122787     0.620229
64645      64645     0.620229
91500      91500     0.620229

In [69]:
#TABLA FINAL DE RECOMENDACIONES
movies_df.set_index('movieId')
recom.set_index('movieId')
movies_df_position = movies_df.join(recom, lsuffix = '_key', on = 'movieId', how = 'right', validate='many_to_many')
movies_df_position = movies_df_position.sort_values(by='ponderation', ascending=False)
movies_df_position.head(20)

,movieId_key,title,genres,year,movieId,ponderation
24565,115479,"Whip Hand, The","[Action, Adventure, Crime, Drama, Sci-Fi, Thri...",1951,115479,0.748092
15562,79132,Inception,"[Action, Crime, Drama, Mystery, Sci-Fi, Thrill...",2010,79132,0.740458
9000,26701,Patlabor: The Movie,"[Action, Animation, Crime, Drama, Film-Noir, M...",1989,26701,0.721374
4923,5018,Motorama,"[Adventure, Comedy, Crime, Drama, Fantasy, Mys...",1991,5018,0.696565
196,198,Strange Days,"[Action, Crime, Drama, Mystery, Sci-Fi, Thriller]",1995,198,0.683206
14397,71999,Aelita: The Queen of Mars,"[Action, Adventure, Drama, Fantasy, Romance, S...",1924,71999,0.679389
16055,81132,Rubber,"[Action, Adventure, Comedy, Crime, Drama, Film...",2010,81132,0.673664
13552,67070,Army of One,"[Action, Adventure, Crime, Drama, Mystery, Thr...",1993,67070,0.648855
12720,59844,Honor Among Thieves,"[Action, Adventure, Crime, Drama, Mystery, Thr...",1968,59844,0.648855
18239,91056,Batman and Robin,"[Action, Adventure, Crime, Drama, Sci-Fi]",1949,91056,0.633588
2900,2985,RoboCop,"[Action, Crime, Drama, Sci-Fi, Thriller]",1987,2985,0.629771
15073,76153,Lupin III: First Contact,"[Action, Animation, Comedy, Crime, Drama, Myst...",2002,76153,0.629771
15001,75408,Lupin III: Sweet Lost Night,"[Action, Animation, Comedy, Crime, Drama, Myst...",2008,75408,0.629771
10427,37462,Wedlock,"[Action, Crime, Drama, Sci-Fi, Thriller]",1991,37462,0.629771
515,519,RoboCop 3,"[Action, Crime, Drama, Sci-Fi, Thriller]",1993,519,0.629771
12873,60684,Watchmen,"[Action, Drama, Mystery, Sci-Fi, Thriller, IMAX]",2009,60684,0.627863
7763,8361,"Day After Tomorrow, The","[Action, Adventure, Drama, Sci-Fi, Thriller]",2004,8361,0.620229
26442,122787,The 39 Steps,"[Action, Adventure, Comedy, Crime, Drama, Thri...",1959,122787,0.620229
9403,27618,"Sound of Thunder, A","[Action, Adventure, Drama, Sci-Fi, Thriller]",2005,27618,0.620229
31427,141385,Humanity's End,"[Action, Adventure, Drama, Sci-Fi, Thriller]",2009,141385,0.620229

In [70]:
# TRATAMIENTO DE DATOS

posters_df['year'] = posters_df.Title.str.extract('(\(\d{4}\))', expand = False)
posters_df['year'] = posters_df.Title.str.extract('(\d{4})', expand = False)

# REMOVER EL AÑO

posters_df['Title'] = posters_df['Title'].str.replace('(\(\d{4}\))','',regex = True).str.strip()


posters_df

,imdbId,Imdb Link,Title,IMDB Score,Genre,Poster,year
0,114709,http://www.imdb.com/title/tt114709,Toy Story,8.3,Animation|Adventure|Comedy,https://images-na.ssl-images-amazon.com/images...,1995
1,113497,http://www.imdb.com/title/tt113497,Jumanji,6.9,Action|Adventure|Family,https://images-na.ssl-images-amazon.com/images...,1995
2,113228,http://www.imdb.com/title/tt113228,Grumpier Old Men,6.6,Comedy|Romance,https://images-na.ssl-images-amazon.com/images...,1995
3,114885,http://www.imdb.com/title/tt114885,Waiting to Exhale,5.7,Comedy|Drama|Romance,https://images-na.ssl-images-amazon.com/images...,1995
4,113041,http://www.imdb.com/title/tt113041,Father of the Bride Part II,5.9,Comedy|Family|Romance,https://images-na.ssl-images-amazon.com/images...,1995
...,...,...,...,...,...,...,...
40103,83168,http://www.imdb.com/title/tt83168,Tanya's Island,4.3,Drama,https://images-na.ssl-images-amazon.com/images...,1980
40104,82875,http://www.imdb.com/title/tt82875,Pacific Banana,4.7,Comedy,https://images-na.ssl-images-amazon.com/images...,1981
40105,815258,http://www.imdb.com/title/tt815258,Werewolf in a Womens Prison,4.5,Horror,https://images-na.ssl-images-amazon.com/images...,2006
40106,79142,http://www.imdb.com/title/tt79142,Xiao zi ming da,6.5,Action|Comedy,https://images-na.ssl-images-amazon.com/images...,1979
40107,70710,http://www.imdb.com/title/tt70710,Snatched,6.5,Crime|Drama|Thriller,NaN,1973

In [71]:
#Limpiamos datos innecesarios

posters_df = posters_df.drop('Imdb Link', axis=1).drop('year', axis=1).drop('IMDB Score', axis=1).drop('Genre', axis=1)

posters_df

,imdbId,Title,Poster
0,114709,Toy Story,https://images-na.ssl-images-amazon.com/images...
1,113497,Jumanji,https://images-na.ssl-images-amazon.com/images...
2,113228,Grumpier Old Men,https://images-na.ssl-images-amazon.com/images...
3,114885,Waiting to Exhale,https://images-na.ssl-images-amazon.com/images...
4,113041,Father of the Bride Part II,https://images-na.ssl-images-amazon.com/images...
...,...,...,...
40103,83168,Tanya's Island,https://images-na.ssl-images-amazon.com/images...
40104,82875,Pacific Banana,https://images-na.ssl-images-amazon.com/images...
40105,815258,Werewolf in a Womens Prison,https://images-na.ssl-images-amazon.com/images...
40106,79142,Xiao zi ming da,https://images-na.ssl-images-amazon.com/images...
40107,70710,Snatched,NaN

In [72]:
posters_df = posters_df[['Title', 'Poster']]

movies_df_position = pd.merge(movies_df_position, posters_df, left_on='title', right_on='Title', how='left')

movies_df_position = movies_df_position[movies_df_position["Poster"].notna()]

top20 = movies_df_position.head(20)

for i, row in top20.iterrows():
    print(f"{row['title']} {row['ponderation']}")
    display(Image(url=row["Poster"], width=150, height=200))

Inception 0.7404580152671756

Patlabor: The Movie 0.7213740458015268

Motorama 0.6965648854961832

Strange Days 0.683206106870229

Rubber 0.6736641221374046

Army of One 0.648854961832061

Batman and Robin 0.6335877862595419

RoboCop 0.6297709923664122

RoboCop 0.6297709923664122

Wedlock 0.6297709923664122

RoboCop 3 0.6297709923664122

Watchmen 0.6278625954198473

The 39 Steps 0.6202290076335878

The 39 Steps 0.6202290076335878

The 39 Steps 0.6202290076335878

Humanity's End 0.6202290076335878

Children of Men 0.6202290076335878

Jumper 0.6202290076335878

Jumper 0.6202290076335878

The Wrecking Crew 0.6202290076335878